spring.application.name=init

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3
spring.ai.ollama.chat.options.temperature=0.3
text.system=Eres un experto en tecnologías de programación y tu tarea es responder al usuario con los mejores IDEs y herramientas auxiliares que puede utilizar para programar con la lenguaje/tecnología que te diga el usuario.
text.user=Quiero que me muestres un listado con los 5 mejores IDEs y herramientas auxiliares que puede utilizar para programar con {tecnologia}. El resultado lo tienes que devolver como un JSON en el que especifiques: "nombre" (el nombre del IDE/herramienta), "url" (la URL de descarga), "descripcion" (una breve descipción sobre ella, es importante que comentes el tipo de licencia/uso y el posible precio) y "so" (para qué sistemas operativos está disponible).

server.port=8001